### PR TITLE
document why people should use cobrexa

### PR DESCRIPTION
**Pull request by exaexa**
refs #58 thx @oxinabox for reminding me to finally do this

### CODE REVIEW

**Comment by exaexa** [comment]
@oxinabox comments welcome

**Review by stelmo — APPROVED** [review]

**Comment by stelmo** [comment]
Closes #59

**Comment by oxinabox** [comment]
A thing that is missing for me is a feature list of basic/advanced FBA features/varients.
Like knockout, thermodynamic constraints etc etc
Ideally with contrast to other tools but even without

**Comment by exaexa** [comment]
> A thing that is missing for me is a feature list of basic/advanced FBA features/varients. Like knockout, thermodynamic constraints etc etc Ideally with contrast to other tools but even without

Yeah that's what we kinda transcended, the "variants" are usually 1 line of extra math and in my very humble uneducated layman opinion (read: only phd from these things) should never be used "as is" or included in any package verbatim, because people should be able to (and should do) specify a variant that best matches the task and data they have available at hand. CTs.jl make this straightforward.

Re the actual listing- if we try, it is always going to be incomplete or out of date, so I guess I'll just link the examples listing from the docs, most of the "frontendy" things that we have are listed there, and it stays synced because we use that as tests (and there is 💯% cov requirement).

**Comment by exaexa** [comment]
ok this looks quite happy to me now, thanks for suggestions. I'm not a fan of the "feature comparison matrices" req from #58 so I just ignored it here (that should be a topic for a comprehensive review study), in case it's Really Required here for whatever reason please reopen #58.

Thanks!

**Pull request merged**
