### PR TITLE
try switching the tutorials from glpk to highs, see what happens

### LINKED ISSUE #57: Switch all documentation over from GLPK to HiGHs
## Target functionality

The docs on occasion reference using GLPK.
Use of GLPK should generally be discouraged at this point.

To quote the JuMP issue (they were talking about MILP but point stands for LP as well) https://github.com/jump-dev/JuMP.jl/issues/2878

> ... examples in the JuMP documentation use GLPK... However, it has the down-side of being the first solver that new users see when they read the docs.
> 
> We should switch ... examples to HiGHS because it's **faster, more robust, and being actively developed.**

(Emphasis mine)

To make kinda clear why consider FBA on yeast.
(I can make this a MWE if wanted but I don't think needed, its on [this SBML](https://github.com/SysBioChalmers/yeast-GEM/blob/main/model/yeast-GEM.xml))
Second runtime on each, so it is all compiled

```julia-repl
julia> @time sol_glpk = flux_balance_analysis(model, optimizer = GLPK.Optimizer);
  1.387430 seconds (838.36 k allocations: 49.660 MiB)
julia> @time sol_clp = flux_balance_analysis(model, optimizer = Clp.Optimizer);
  0.405093 seconds (805.17 k allocations: 49.605 MiB)
julia> @time sol_highs = flux_balance_analysis(model, optimizer = HiGHS.Optimizer);
  0.154727 seconds (827.32 k allocations: 50.077 MiB)
```

## Desired output

The docs should reference using HiGHs instead.

## Optional: Suggestions for implementation

Basically just change every reference to GLPK [found here](https://github.com/search?q=repo%3ACOBREXA%2FCOBREXA.jl%20GLPK&type=code) to be HiGHs.

### PR DESCRIPTION
**Pull request by exaexa**
closes #57

### CODE REVIEW

**Comment by exaexa** [comment]
(Not to be merged until HiGHS is proven less than or equally as surprising as GLPK.)

**Comment by exaexa** [comment]
So there's an issue with the solution of MMDF, looks to be quite a bit off the expected solution. Maybe that's biased by us comparing from previous solvers, but the difference is MAN WAY OFF all acceptable tolerances.

As the other issue HiGHS is for whatever reason verbose by default (rule of silence where?!). Can that be somehow disabled globally so that we don't need to put an extra solver setting to literally all analysis function calls?

**Comment by odow** [comment]
You can use `JuMP.set_silent(model)` or `optimizer = MOI.OptimizerWithAttributes(HiGHS.Optimizer, MOI.Silent() => true)`.

You could probably also add a `; silent` flag as well. Different solvers have different defaults.

For the error: what are the objective values of the two solutions? Is it `mmdf_solution.min_driving_force `? If so, HiGHS is finding a solution with that objective value. Do you have evidence that the [-6, -5] solution is unique? Perhaps there are multiple (near) optimal solutions?

**Comment by exaexa** [comment]
@odow ok that sounds like we will have some default settings applied to all problems, and probably have an explicit "unsilence" setting instead.

Re the value, the "min driving force" is the maximized objective (it's called "Maximize the Minimal Driving Force" or so). Might not be a HiGHS problem, the code is new, maybe we messed up something entirely different. The range is used there instead of tolerance (I didn't even want to pretend we have an exact number there).

**Comment by jajhall** [comment]
I see what you mean by the "minimal surprise" rule. Looking at the logging for the MMDF model, there's nothing to suggest that HiGHS is concerned about the solution process (and it's just a small LP) so the suggestion of @odow about non-uniqueness is the most likely reason, and the objective function test is wise.

More generally, it is common for LPs to have non-unique solutions, so COBREXA folk can't expect HiGHS to get the same solution as GLPK.

**Comment by exaexa** [comment]
> More generally, it is common for LPs to have non-unique solutions, so COBREXA folk can't expect HiGHS to get the same solution as GLPK.

yeah I know. The tested value should be the objective value, which should be same (sans precision) for all solvers, right?

Anyway might be the case that simply the test is wrong. I'm in summer mode now, will try to have a deeper look asap :D

**Comment by odow** [comment]
I notice that this is "log_concentrations":
https://github.com/COBREXA/COBREXA.jl/blob/6134fa6e5ac22e453ceb7fa2f218dfaa9deeedfe/docs/src/examples/05c-mmdf.jl#L124

Does this mean the primal solution is between 1e-6 and 1e-5? If so, that is close to HiGHS' default feasibility tolerance of 1e-7, and the value of `-13` is essentially "zero".

I would strongly encourage you to reformulate your models to keep non-zero primal values above 1e-4 or so.

**Comment by exaexa** [comment]
@odow ah OK issue solved, the test is for non-objective value. As I said previously, currently in summer mode with a whimsy cellphone, didn't notice this issue 😅 

(maybe we should actually abstract out the solver package and test at least 2 different ones :D )

The concentrations are logarithmized already, the values that the solvers see are just the exponents (ie. relatively sane scale).

**Comment by exaexa** [comment]
TODO: to fix the test while keeping it sane let's demonstrate concentration variability analysis in this

**Review by stelmo — APPROVED** [review]

**Pull request merged**
