### PR TITLE
Small changes to MMDF

### PR DESCRIPTION
**Pull request by stelmo**

### CODE REVIEW

**Comment by stelmo** [comment]
Need some way to tell the testing interface to ignore the plotting calls. Maybe plotting is not worth it here, but it could be nice to show plots in the showcase examples

**Comment by exaexa** [comment]
rebasegun applied

**Comment by stelmo** [comment]
Took out the plotting, should be g2g now @exaexa

**Review by exaexa — APPROVED** [review]
Rewrote a bit closer to the original form, avoiding a few gotchas here and there. Most notably the ConstraintTree is now really tiny, which is cool

**Pull request merged**
